### ISSUE TITLE
BleakError object is not subscriptable

### ISSUE THREAD

**Issue by blackshoals** [vanstinator/melnor-bluetooth#21]
'poetry install python cli.py' runs and finds 1 of 2 Melnor devices.  Connection fails with:

`~/Downloads/melnor-bluetooth-main$ poetry run python cli.py
58:93:D8:37:29:59
Found device: Device(
    battery=0
    valves=(
      Valve(id=0|is_watering=False|manual_minutes=20|seconds_left=0)
      Valve(id=1|is_watering=False|manual_minutes=20|seconds_left=0)
      Valve(id=2|is_watering=False|manual_minutes=20|seconds_left=0)
      Valve(id=3|is_watering=False|manual_minutes=20|seconds_left=0)
    )
)
Connecting to: 58:93:D8:37:29:59
Failed to connect to: 58:93:D8:37:29:59
Traceback (most recent call last):
  File "/home/ian/Downloads/melnor-bluetooth-main/cli.py", line 88, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/ian/Downloads/melnor-bluetooth-main/cli.py", line 42, in main
    await device.fetch_state()
  File "/home/ian/Downloads/melnor-bluetooth-main/melnor_bluetooth/device.py", line 215, in fetch_state
    self._battery = parse_battery_value(some_bytes)
  File "/home/ian/Downloads/melnor-bluetooth-main/melnor_bluetooth/parser/battery.py", line 4, in parse_battery_value
    if (bytes[0] & 255 == 238) and (bytes[1] & 255 == 238):
TypeError: 'BleakError' object is not subscriptable
`

**Comment by blackshoals** [comment]
Commenting out lines 214,215 in device.py to bypass the call to the parser/battery.py allows the program to proceed.

**Comment by vanstinator** [comment]
Thanks for the report! 

I'm not able to reproduce this on any of my devices. What device/make/model are you using?

**Comment by blackshoals** [comment]
Hi, I have to 3 of the Melnor 65127-AMZ 2 zone Bluetooth Water timers to control 6 zones.
