### ISSUE TITLE
CLI example positional arguments error

### ISSUE THREAD

**Issue by blackshoals** [vanstinator/melnor-bluetooth#23]
Error when running a test script (turnon1.py) to turn on a valve: 

import asyncio
from melnor_bluetooth.device import Device

address = 'xxxxx' # fill with your device mac address

async def main():
    device = Device(address, 4)
    await device.connect()
    device.zone1.is_watering = True;
    await device.push_state();
    await device.disconnect();

asyncio.run(main())

gives:

Traceback (most recent call last):
  File "/home/ian/Downloads/melnor-bluetooth/turnon1.py", line 16, in <module>
    asyncio.run(main())
  File "/home/ian/anaconda3/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/ian/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/ian/Downloads/melnor-bluetooth/turnon1.py", line 8, in main
    device = Device(address, 4)
**TypeError: __init__() takes 2 positional arguments but 3 were given**

**Comment by blackshoals** [comment]
The issue seems related to Line 135 of device.py. Can get the script to run by removing one argument from "device = Device(address, 4)"  to "device = Device(address)".

**Comment by vanstinator** [comment]
Fixed!
