### ISSUE TITLE
Feature request : Retry on "Failed to Connect"

### ISSUE THREAD

**Issue by blackshoals** [vanstinator/melnor-bluetooth#25]
Due to the lag on device connect/disconnect it would be great to have a retry on a failure to connect to ensure the next command goes through.

`Failed to connect to: 58:93:D8:3E:D2:DB
Disconnected from: 58:93:D8:3E:D2:DB
Traceback (most recent call last):
  File "/home/ian/Downloads/melnor-bluetooth/turnoff1.py", line 16, in <module>
    asyncio.run(main())
  File "/home/ian/anaconda3/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/ian/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/ian/Downloads/melnor-bluetooth/turnoff1.py", line 13, in main
    await device.push_state();
  File "/home/ian/Downloads/melnor-bluetooth/melnor_bluetooth/device.py", line 240, in push_state
    on_off.handle,
AttributeError: 'NoneType' object has no attribute 'handle'
`

**Comment by vanstinator** [comment]
I'll be reworking the library fairly significantly to better support the new bluetooth hooks in Home Assistant. I'll see if/where this makes sense to land during that work.

**Comment by vanstinator** [comment]
Commands now guard against disconnected states and will attempt to reconnect if there's an issue
