### ISSUE TITLE
Only one device available

### ISSUE THREAD

**Issue by blackshoals** [vanstinator/melnor-bluetooth#26]
When trying to run to a second device using a different MAC address the turn on script fails. The scanner seems to see all the available devices, but only connects to one.

`Connecting to: 58:93:D8:3E:D2:DB
Disconnected from: 58:93:D8:3E:D2:DB
Failed to connect to: 58:93:D8:3E:D2:DB
Traceback (most recent call last):
  File "/home/ian/Downloads/melnor-bluetooth/turnon1.py", line 17, in <module>
    asyncio.run(main())
  File "/home/ian/anaconda3/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/ian/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/ian/Downloads/melnor-bluetooth/turnon1.py", line 12, in main
    device.zone2.is_watering = True;
  File "/home/ian/Downloads/melnor-bluetooth/melnor_bluetooth/device.py", line 304, in zone2
    if self._valve_count > 1:
AttributeError: 'Device' object has no attribute '_valve_count'
`

**Comment by vanstinator** [comment]
This admittedly isn't a well defined case. The primary consumer for this lib is Home Assistant and the state machine there handles separate instances of `Device` for me.

I'll be refactoring this library quite a bit to better support some new bluetooth best-practices in Home Assistant. That work will likely significantly change the outer loop for handling devices.
